---
name: registry

services:
  registry:
    image: registry:2
    container_name: registry
    ports:
      - 5000:5000
    volumes:
      - registry:/var/lib/registry
    restart: always

volumes:
  registry:
