---
x-logging: &default-logging
  logging:
    options:
      max-size: 10m
      max-file: 5

name: lemp
services:
  web:
    image: nginx:${NGINX_IMAGE_TAG}
    container_name: www
    ports:
      - 80:80
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx:/etc/nginx/conf.d
    networks:
      lempnet:
        ipv4_address: 172.30.0.100
    <<: *default-logging
    healthcheck:
      test: ["CMD-SHELL","curl --fail http://localhost/index.html"]
      interval: 5s
      retries: 2
      start_period: 2s

  php:
    image: php:${PHP_IMAGE_TAG}
    container_name: php
    networks:
      lempnet:
        ipv4_address: 172.30.0.150
      dbnet:
    volumes:
      - ./html:/var/www/html
    restart: always
    <<: *default-logging

  mariadb:
    image: mariadb:${MARIADB_IMAGE_TAG}
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_PASSWORD}
    networks:
      dbnet:
    <<: *default-logging

volumes:
  mariadb:

networks:
  lempnet:
    ipam:
      config:
        - subnet: 172.30.0.0/24
          gateway: 172.30.0.254
    driver_opts:
      com.docker.network.bridge.name: lempnet0
  dbnet:
